version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecosync
  
  frontend:
    build:
      context: ./client
      # target: dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/usr/src/app
    env_file:
      - .env

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    # volumes:
    #   - ./server:/usr/src/app
    env_file:
      - .env

